name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *" # Runs every 12 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v2

      # Generate the snake SVG
      - uses: Platane/snk@v2.2.1
        id: snake-gif
        with:
          github_user_name: adiManethia # Replace with your GitHub username
          svg_out_path: dist/github-contribution-grid-snake.svg
          
      # Push the SVG to the output branch
      - uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
